### ISSUE TITLE
Lcd custom dashboard

### ISSUE THREAD

**Issue by zx0CF1** [HerrRiebmann/KDS2Bluetooth#6]
First of all congratulations for your work dude.

Based on your research i will try to develop a custom lcd dashboard like aim ones. 

If you have any advice, I'd be happy to hear it.

**Comment by HerrRiebmann** [comment]
Thanks, mate!
I´m not sure if this will be the right approach. The dashboard has an own data-line which constantly transferes those informations. And some additional things, like MIL, indicator, milage, and so on. You won´t get those infos from the diagnostic port.
And it´s quite slow with around ~7 messages per second.

This is what you want to have :)
https://youtu.be/WHeit69LpBU

**Comment by zx0CF1** [comment]
> Thanks, mate!
> 
> I´m not sure if this will be the right approach. The dashboard has an own data-line which constantly transferes those informations. And some additional things, like MIL, indicator, milage, and so on. You won´t get those infos from the diagnostic port.
> 
> And it´s quite slow with around ~7 messages per second.
> 
> 
> 
> This is what you want to have :)
> 
> https://youtu.be/WHeit69LpBU

Definitly i have to take a very deep look into it. Btw do you know what protocol its used for the Dashboard communication? 

Thanks mate 🙂

**Comment by HerrRiebmann** [comment]
I think this is a combination.
As far as I know, the communication between the dash and ECU is also K-Line. And anything else seem to be just singnals.
But I have not tried it myself, yet.

If you get any information about that (_maybe from the video maker_), just let me know :)

**Comment by Roughd1433** [comment]
If you look at the description under the video he explains how he did it and there are git hub links to code. Uses kwp2000.

**Comment by HerrRiebmann** [comment]
> If you look at the description under the video he explains how he did it and there are git hub links to code. Uses kwp2000.

Okay, so he uses my and asters code to communicate to the ECU and grabs the rest directly from the cables on the dash.

I´ll push some updates to my code during the christmas time. Maybe it will help you out a bit.
But my concern still will be, that the updaterate is quite bad. And as Mario wrote under the video, the ODO meter is just a calculation by speed. So from my opinion a guess, which will not work out to replace a dash.

**Comment by aster94** [comment]
> This is what you want to have :) https://youtu.be/WHeit69LpBU

Thanks @HerrRiebmann for the video, very nice!
