### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by SaLuci** [HerrRiebmann/KDS2Bluetooth#8]
I've got some ESP32 laying around, so instead of buying a HC-06 id like to use one of those.
Should be as simple as changing 
`SoftwareSerial BT (8,7)`
To 
`BluethoothSerial BT` (and including the BluetoothSerial library)

Obviously the BT Commands wont work, but that shouldn't be a problem, right? (I guess id have to delete/rewrite the corresponding code)

I cant test it right now, since im not home.
Just wanted your opinion.

Thank you for taking the time and documenting your code (and making it available to the public) really appreciate it.

**Comment by HerrRiebmann** [comment]
Hi, yes that is definitely possible. 
I also already done it for testing purpose. You also need to uncommented the RAM size and temperature calculation. The compiler warnings will lead you to those lines 💪🏻
I'm on vacation right now and cannot give you more advice. 
But that's easy and you will make it anyways 😎

**Comment by SaLuci** [comment]
Thank you for the response.
I'll keep that in mind.

Im closing the issue now
